# Generated by Django 5.2 on 2025-08-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='Untitled Note', max_length=200),
        ),
    ]
